export const FETCHED_SPELLS = 'FETCHING_SPELLS'

export const LOADING_SPELLS = 'LOADING_SPELLS'

export const SELECT_SPELLS = 'SELECT_SPELLS'

export const CHANGE_SEARCH_TEXT = 'CHANGE_SEARCH_TEXT'

export const FETCHED_CHARS = 'FETCHED_CHARS'

export const LOADING_CHARS = 'LOADING_CHARS'
